---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tunnel.mcmumf.dev
  resources:
  - tunnelconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunnel.mcmumf.dev
  resources:
  - tunnelconnections/finalizers
  verbs:
  - update
- apiGroups:
  - tunnel.mcmumf.dev
  resources:
  - tunnelconnections/status
  verbs:
  - get
  - patch
  - update
