---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cname.mcmumf.dev
  resources:
  - cnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cname.mcmumf.dev
  resources:
  - cnames/finalizers
  verbs:
  - update
- apiGroups:
  - cname.mcmumf.dev
  resources:
  - cnames/status
  verbs:
  - get
  - patch
  - update
