# permissions for end users to view tunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zero-trust-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: tunnel-viewer-role
rules:
- apiGroups:
  - zto.mcmumf.dev
  resources:
  - tunnels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zto.mcmumf.dev
  resources:
  - tunnels/status
  verbs:
  - get
