# This rule is not used by the project zero-trust-orchestrator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to tunnel.mcmumf.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zero-trust-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: tunnelconnection-viewer-role
rules:
- apiGroups:
  - tunnel.mcmumf.dev
  resources:
  - tunnelconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tunnel.mcmumf.dev
  resources:
  - tunnelconnections/status
  verbs:
  - get
