apiVersion: tunnel.mcmumf.dev/v1alpha1
kind: TunnelConnection
metadata:
  labels:
    app.kubernetes.io/name: zero-trust-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: tunnelconnection-sample
spec:
  # TODO(user): Add fields here
