apiVersion: zto.mcmumf.dev/v1alpha1
kind: Tunnel
metadata:
  labels:
    app.kubernetes.io/name: zero-trust-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: tunnel-sample
spec:
  # TODO(user): Add fields here
